# Generated by Django 5.2.8 on 2025-11-25 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('tipo', models.CharField(choices=[('publica', 'Pública'), ('privada', 'Privada'), ('social', 'Social / ONG'), ('educativa', 'Educativa'), ('partido', 'Partido político'), ('otro', 'Otro')], default='publica', max_length=20)),
                ('ambito', models.CharField(blank=True, help_text='Municipal, estatal, federal, regional, nacional, etc.', max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(default='México', max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=255)),
                ('bio_corta', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('es_actual', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='redpolitica.institucion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='redpolitica.persona')),
            ],
            options={
                'ordering': ['-fecha_inicio', 'persona'],
            },
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('familiar', 'Familiar'), ('amistad', 'Amistad / cercanía personal'), ('socio', 'Socios / negocios'), ('grupo_politico', 'Mismo grupo político'), ('laboral', 'Relación laboral previa'), ('otro', 'Otro tipo de relación')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fuente', models.CharField(blank=True, help_text='Referencia de la fuente: nota, comunicado, liga, etc.', max_length=500)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_destino', to='redpolitica.persona')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_origen', to='redpolitica.persona')),
            ],
            options={
                'verbose_name': 'Relación entre personas',
                'verbose_name_plural': 'Relaciones entre personas',
            },
        ),
    ]
