# Generated by Django 5.2.8 on 2025-11-25 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redpolitica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relacion',
            options={'verbose_name': 'Relación', 'verbose_name_plural': 'Relaciones'},
        ),
        migrations.RemoveField(
            model_name='relacion',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='institucion',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fin del periodo (ej. fin de administración).', null=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Inicio del periodo (ej. inicio de administración).', null=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='padre',
            field=models.ForeignKey(blank=True, help_text='Institución de la cual depende (ej. Municipio, Poder Ejecutivo, Ayuntamiento).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijas', to='redpolitica.institucion'),
        ),
        migrations.AlterField(
            model_name='relacion',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relacion',
            name='fuente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='relacion',
            name='tipo',
            field=models.CharField(choices=[('familiar', 'Relación familiar'), ('amistad', 'Amistad / cercanía personal'), ('socio', 'Socios / negocios'), ('grupo_politico', 'Mismo grupo político'), ('laboral', 'Relación laboral'), ('otro', 'Otro tipo de relación')], default='otro', max_length=50),
        ),
    ]
