# Generated by ChatGPT on 2025-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redpolitica", "0005_alter_legislatura_periodo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodoadministrativo",
            name="nivel",
            field=models.CharField(
                choices=[("ESTATAL", "Estatal"), ("MUNICIPAL", "Municipal"), ("FEDERAL", "Federal")],
                max_length=20,
            ),
        ),
    ]
