# Generated by Django 5.2.8 on 2025-12-30 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redpolitica', '0006_alter_periodoadministrativo_nivel'),
        ('redpolitica', '0006_remove_periodoadministrativo_institucion_raiz'),
    ]

    operations = [
    ]
