# Generated by Django 5.2.8 on 2026-01-01 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redpolitica', '0007_merge_20251230_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitanciaPartidista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('militante', 'Militante'), ('dirigente', 'Dirigente'), ('candidato', 'Candidato'), ('externo', 'Externo')], max_length=20, null=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['persona_id', 'fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='cargo_clase',
            field=models.CharField(blank=True, db_index=True, help_text="Clase canónica para agrupamiento (ej. 'diputacion_local', 'diputacion_federal', 'senaduria', 'presidencia_municipal', 'secretaria').", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='cargo_codigo',
            field=models.SlugField(blank=True, help_text='Código/slug estable derivado de cargo_clase (opcional).', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='cargo_titulo',
            field=models.CharField(blank=True, help_text="Título canónico para UI (ej. 'Diputación local', 'Senaduría').", max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['periodo'], name='redpolitica_periodo_e7c279_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['persona', 'periodo'], name='redpolitica_persona_2c5663_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['institucion', 'periodo'], name='redpolitica_institu_895766_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['cargo_clase'], name='redpolitica_cargo_c_d0fc3f_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['cargo_codigo'], name='redpolitica_cargo_c_1298ce_idx'),
        ),
        migrations.AddField(
            model_name='militanciapartidista',
            name='partido',
            field=models.ForeignKey(help_text="Selecciona una Institución cuyo tipo sea 'Partido político'.", limit_choices_to={'tipo': 'partido'}, on_delete=django.db.models.deletion.PROTECT, related_name='militancias_recibidas', to='redpolitica.institucion'),
        ),
        migrations.AddField(
            model_name='militanciapartidista',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='militancias', to='redpolitica.persona'),
        ),
        migrations.AddIndex(
            model_name='militanciapartidista',
            index=models.Index(fields=['persona', 'fecha_inicio'], name='redpolitica_persona_c6ce22_idx'),
        ),
        migrations.AddIndex(
            model_name='militanciapartidista',
            index=models.Index(fields=['partido', 'fecha_inicio'], name='redpolitica_partido_083b4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='militanciapartidista',
            constraint=models.UniqueConstraint(fields=('persona', 'partido', 'fecha_inicio'), name='uniq_militancia_persona_partido_inicio'),
        ),
    ]
