# Generated by Django 5.2.8 on 2026-01-01 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redpolitica', '0009_backfill_cargo_clase'),
    ]

    operations = [
    ]
