# Generated by Django 5.2.8 on 2026-01-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redpolitica", "0010_backfill_cargo_clase"),
    ]

    operations = [
        migrations.AddField(
            model_name="institucion",
            name="aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="persona",
            name="aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="topic",
            name="aliases",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
