# Generated by Django 5.2.8 on 2026-01-03 20:03

import json

from django.db import migrations, models


def _normalize_aliases_value(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, list):
        return ", ".join([str(item).strip() for item in value if str(item).strip()])
    if not isinstance(value, str):
        return str(value).strip()
    stripped = value.strip()
    if stripped.startswith("["):
        try:
            parsed = json.loads(stripped)
        except json.JSONDecodeError:
            parsed = None
        if isinstance(parsed, list):
            return ", ".join([str(item).strip() for item in parsed if str(item).strip()])
    return stripped


def normalize_aliases(apps, schema_editor):
    models_to_update = [
        apps.get_model("redpolitica", "Persona"),
        apps.get_model("redpolitica", "Institucion"),
        apps.get_model("redpolitica", "Topic"),
    ]
    for model in models_to_update:
        for obj in model.objects.all().iterator():
            normalized = _normalize_aliases_value(obj.aliases)
            if obj.aliases != normalized:
                obj.aliases = normalized
                obj.save(update_fields=["aliases"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("redpolitica", "0011_institucion_aliases_persona_aliases_topic_aliases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institucion",
            name="aliases",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="persona",
            name="aliases",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="topic",
            name="aliases",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(normalize_aliases, reverse_code=noop_reverse),
    ]
