# Generated by Django 5.2.8 on 2025-12-18 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('type', models.CharField(choices=[('digital_native', 'Digital nativo'), ('broadcast_with_web', 'Radio/TV con web'), ('print_with_web', 'Impreso con web')], max_length=30)),
                ('home_url', models.URLField(blank=True)),
                ('weight', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'is_active'], name='monitor_med_type_a3dbe6_idx')],
            },
        ),
        migrations.CreateModel(
            name='MediaSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('rss', 'RSS'), ('sitemap', 'Sitemap'), ('section_url', 'Sección/URL'), ('api', 'API'), ('manual_url', 'Manual')], max_length=20)),
                ('url', models.URLField()),
                ('scan_interval_minutes', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('media_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='monitor.mediaoutlet')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('title', models.TextField()),
                ('lead', models.TextField(blank=True)),
                ('authors', models.CharField(blank=True, max_length=400)),
                ('section', models.CharField(blank=True, max_length=200)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(default='es', max_length=10)),
                ('entities_extracted', models.JSONField(blank=True, default=dict)),
                ('quality_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.mediaoutlet')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.mediasource')),
            ],
        ),
        migrations.CreateModel(
            name='IngestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scheduled', 'Programada'), ('manual', 'Manual'), ('retry', 'Reintento')], default='manual', max_length=20)),
                ('time_window_start', models.DateTimeField()),
                ('time_window_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('running', 'Corriendo'), ('success', 'Exitosa'), ('failed', 'Fallida'), ('partial', 'Parcial')], default='queued', max_length=20)),
                ('stats_total_fetched', models.PositiveIntegerField(default=0)),
                ('stats_total_parsed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'started_at'], name='monitor_ing_status_c2a04a_idx'), models.Index(fields=['time_window_start', 'time_window_end'], name='monitor_ing_time_wi_2c80e4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mediasource',
            index=models.Index(fields=['media_outlet', 'is_active'], name='monitor_med_media_o_44dd98_idx'),
        ),
        migrations.AddIndex(
            model_name='mediasource',
            index=models.Index(fields=['last_fetched_at'], name='monitor_med_last_fe_8ed5aa_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['media_outlet', 'published_at'], name='monitor_art_media_o_17ab34_idx'),
        ),
    ]
