# Generated by Django 5.2.8 on 2026-01-02 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=1000, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("raw_html", models.TextField(blank=True)),
                ("text", models.TextField()),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.TextField(blank=True)),
                ("extracted_tags_json", models.JSONField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=20)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nueva"),
                            ("processed", "Procesada"),
                            ("error", "Error"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("error_text", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-published_at", "-fetched_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("ingest", "Ingesta"),
                            ("classify", "Clasificación"),
                            ("all", "Pipeline completo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("error", "Error"),
                            ("running", "En ejecución"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("log_text", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("rss", "RSS"),
                            ("sitemap", "Sitemap"),
                            ("scrape", "Scrape"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("is_active", models.BooleanField(default=True)),
                ("frequency_minutes", models.PositiveIntegerField(default=60)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(
                        choices=[("ok", "OK"), ("error", "Error")],
                        default="ok",
                        max_length=10,
                    ),
                ),
                ("last_error_text", models.TextField(blank=True)),
                ("last_ok_at", models.DateTimeField(blank=True, null=True)),
                ("last_latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("last_new_count", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("central_idea", models.TextField()),
                (
                    "article_type",
                    models.CharField(
                        choices=[
                            ("informativo", "Informativo"),
                            ("opinion", "Opinión"),
                        ],
                        max_length=20,
                    ),
                ),
                ("labels_json", models.JSONField(default=list)),
                ("model_name", models.CharField(max_length=100)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_editor_locked", models.BooleanField(default=False)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification",
                        to="monitor.article",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EditorialReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("before_json", models.JSONField()),
                ("after_json", models.JSONField()),
                ("reason_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="monitor.article",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BatchSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_json", models.JSONField()),
                ("affected_count", models.PositiveIntegerField(default=0)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_suggestions",
                        to="monitor.editorialreview",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Mention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("persona", "Persona"),
                            ("institucion", "Institución"),
                            ("tema", "Tema"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_id", models.IntegerField()),
                ("target_name", models.CharField(max_length=255)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positivo", "Positivo"),
                            ("neutro", "Neutro"),
                            ("negativo", "Negativo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField()),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="monitor.classification",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence"],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="monitor.source",
            ),
        ),
    ]
