# Generated by ChatGPT on 2025-01-01
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=120)),
                ("entity_type", models.CharField(blank=True, max_length=120)),
                ("entity_id", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(blank=True, max_length=40)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BenchmarkSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("label", models.CharField(max_length=200)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Correction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "scope",
                    models.CharField(
                        choices=[("article", "Artículo"), ("story", "Historia")],
                        max_length=10,
                    ),
                ),
                ("target_id", models.PositiveIntegerField()),
                ("field_name", models.CharField(max_length=120)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("explanation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("apply_to", models.CharField(default="client", max_length=40)),
                (
                    "created_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EditorialTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                ("is_global", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JobLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("job_name", models.CharField(max_length=120)),
                ("status", models.CharField(max_length=40)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("outlet", models.CharField(max_length=200)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("rss", "RSS"), ("sitemap", "Sitemap"), ("html", "HTML"), ("api", "API")],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["outlet", "name"],
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title_base", models.TextField()),
                ("lead_base", models.TextField(blank=True)),
                ("main_topic_id", models.CharField(blank=True, max_length=120)),
                ("time_window_start", models.DateTimeField()),
                ("time_window_end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("propuesta", "Propuesta"), ("confirmada", "Confirmada"), ("corregida", "Corregida")],
                        default="propuesta",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-time_window_start", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TrainingExample",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope", models.CharField(max_length=10)),
                ("input_features", models.JSONField(blank=True, default=dict)),
                ("label", models.JSONField(blank=True, default=dict)),
                ("explanation", models.TextField()),
                ("provenance", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "correction",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="training_examples", to="monitor.correction"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(max_length=1000, unique=True)),
                ("canonical_url", models.URLField(blank=True, max_length=1000)),
                ("title", models.TextField()),
                ("lead", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("outlet", models.CharField(blank=True, max_length=200)),
                ("language", models.CharField(default="es", max_length=10)),
                ("hash_dedupe", models.CharField(db_index=True, max_length=64)),
                ("raw_html", models.TextField(blank=True)),
                (
                    "pipeline_status",
                    models.CharField(
                        choices=[
                            ("ingested", "Ingestada"),
                            ("normalized", "Normalizada"),
                            ("classified", "Clasificada"),
                            ("clustered", "Clusterizada"),
                            ("aggregated", "Agregada"),
                            ("digested", "En síntesis"),
                            ("error", "Error"),
                        ],
                        default="ingested",
                        max_length=20,
                    ),
                ),
                ("pipeline_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="monitor.source")),
            ],
            options={
                "ordering": ["-published_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ClassificationRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model_name", models.CharField(max_length=120)),
                ("model_version", models.CharField(blank=True, max_length=80)),
                ("prompt_version", models.CharField(blank=True, max_length=80)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("cost", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ("tokens", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "En cola"), ("running", "Corriendo"), ("success", "Exitosa"), ("failed", "Fallida")],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="classification_runs", to="monitor.article")),
            ],
        ),
        migrations.CreateModel(
            name="DecisionTrace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("field_name", models.CharField(max_length=120)),
                ("value", models.CharField(max_length=250)),
                ("confidence", models.FloatField(default=0.0)),
                ("rationale", models.TextField(blank=True)),
                (
                    "classification_run",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="decision_traces", to="monitor.classificationrun"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Extraction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("informativo", "Informativo"),
                            ("opinion", "Opinión"),
                            ("boletin", "Boletín"),
                            ("analisis", "Análisis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("federal", "Federal"), ("estatal", "Estatal"), ("municipal", "Municipal")],
                        max_length=20,
                    ),
                ),
                ("institutional_type", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "classification_run",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="extraction", to="monitor.classificationrun"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActorLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("atlas_entity_id", models.CharField(max_length=120)),
                (
                    "atlas_entity_type",
                    models.CharField(choices=[("persona", "Persona"), ("institucion", "Institución")], max_length=20),
                ),
                ("role_in_article", models.CharField(blank=True, max_length=120)),
                (
                    "sentiment",
                    models.CharField(choices=[("positivo", "Positivo"), ("neutro", "Neutro"), ("negativo", "Negativo")], max_length=20),
                ),
                ("sentiment_confidence", models.FloatField(default=0.0)),
                ("rationale", models.TextField(blank=True)),
                (
                    "article",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="actor_links", to="monitor.article"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopicLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("atlas_topic_id", models.CharField(max_length=120)),
                ("confidence", models.FloatField(default=0.0)),
                ("rationale", models.TextField(blank=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="topic_links", to="monitor.article")),
            ],
        ),
        migrations.CreateModel(
            name="StoryActor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("atlas_entity_id", models.CharField(max_length=120)),
                (
                    "atlas_entity_type",
                    models.CharField(choices=[("persona", "Persona"), ("institucion", "Institución")], max_length=20),
                ),
                ("story", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="main_actors", to="monitor.story")),
            ],
        ),
        migrations.CreateModel(
            name="StoryArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_representative", models.BooleanField(default=False)),
                (
                    "added_by",
                    models.CharField(choices=[("ai", "IA"), ("human", "Humano")], default="ai", max_length=10),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="story_articles", to="monitor.article")),
                ("story", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="story_articles", to="monitor.story")),
            ],
        ),
        migrations.CreateModel(
            name="ArticleVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveIntegerField(default=1)),
                ("title", models.TextField()),
                ("lead", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("cleaned_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="monitor.article")),
            ],
            options={
                "ordering": ["-version", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ClientFocus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "entity_type",
                    models.CharField(choices=[("persona", "Persona"), ("institucion", "Institución"), ("tema", "Tema")], max_length=20),
                ),
                ("atlas_id", models.CharField(max_length=120)),
                ("priority", models.PositiveIntegerField(default=1)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="focus_items", to="monitor.client")),
            ],
        ),
        migrations.CreateModel(
            name="DailyExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "En cola"), ("running", "Corriendo"), ("success", "Exitosa"), ("failed", "Fallida")],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_executions", to="monitor.client")),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DailyDigestItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("section", models.CharField(max_length=120)),
                ("rank_score", models.FloatField(default=0.0)),
                ("display_title", models.TextField()),
                ("display_lead", models.TextField(blank=True)),
                ("outlets_chips", models.JSONField(blank=True, default=list)),
                (
                    "daily_execution",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="monitor.dailyexecution"),
                ),
                ("story", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="digest_items", to="monitor.story")),
            ],
            options={
                "ordering": ["rank_score", "id"],
            },
        ),
        migrations.CreateModel(
            name="MetricAggregate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "entity_type",
                    models.CharField(choices=[("persona", "Persona"), ("institucion", "Institución"), ("tema", "Tema")], max_length=20),
                ),
                ("atlas_id", models.CharField(max_length=120)),
                (
                    "period",
                    models.CharField(choices=[("day", "Día"), ("week", "Semana"), ("month", "Mes")], max_length=10),
                ),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("volume", models.PositiveIntegerField(default=0)),
                ("sentiment_pos", models.PositiveIntegerField(default=0)),
                ("sentiment_neu", models.PositiveIntegerField(default=0)),
                ("sentiment_neg", models.PositiveIntegerField(default=0)),
                ("share_opinion", models.FloatField(default=0.0)),
                ("share_informative", models.FloatField(default=0.0)),
                ("persistence_score", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="TagLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("content_type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype")),
                ("tag", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="links", to="monitor.editorialtag")),
            ],
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["event_type", "created_at"], name="monitor_aud_event_t_8a3e3f_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["entity_type", "entity_id"], name="monitor_aud_entity__b6c0ed_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["pipeline_status", "published_at"], name="monitor_art_pipeline_882c0b_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["hash_dedupe"], name="monitor_art_hash_de_3b9b83_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["outlet", "published_at"], name="monitor_art_outlet__072fea_idx"),
        ),
        migrations.AddIndex(
            model_name="articleversion",
            index=models.Index(fields=["article", "version"], name="monitor_art_article_5e7d15_idx"),
        ),
        migrations.AddIndex(
            model_name="actorlink",
            index=models.Index(fields=["atlas_entity_type", "atlas_entity_id"], name="monitor_act_atlas_e_e274cc_idx"),
        ),
        migrations.AddIndex(
            model_name="actorlink",
            index=models.Index(fields=["sentiment"], name="monitor_act_sentime_9b2894_idx"),
        ),
        migrations.AddIndex(
            model_name="classificationrun",
            index=models.Index(fields=["status", "started_at"], name="monitor_cla_status__a5ab86_idx"),
        ),
        migrations.AddIndex(
            model_name="clientfocus",
            index=models.Index(fields=["client", "entity_type"], name="monitor_cli_client__e2f823_idx"),
        ),
        migrations.AddIndex(
            model_name="clientfocus",
            index=models.Index(fields=["atlas_id"], name="monitor_cli_atlas_i_7d1d54_idx"),
        ),
        migrations.AddIndex(
            model_name="correction",
            index=models.Index(fields=["scope", "target_id"], name="monitor_cor_scope_t_6306d2_idx"),
        ),
        migrations.AddIndex(
            model_name="decisiontrace",
            index=models.Index(fields=["field_name"], name="monitor_dec_field_n_375f1e_idx"),
        ),
        migrations.AddIndex(
            model_name="extraction",
            index=models.Index(fields=["content_type", "scope"], name="monitor_ext_content__c8f064_idx"),
        ),
        migrations.AddIndex(
            model_name="metricaggregate",
            index=models.Index(fields=["entity_type", "atlas_id"], name="monitor_met_entity__a8ab6a_idx"),
        ),
        migrations.AddIndex(
            model_name="metricaggregate",
            index=models.Index(fields=["period", "date_start"], name="monitor_met_period__761ffd_idx"),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(fields=["source_type", "is_active"], name="monitor_sou_source__d87d88_idx"),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(fields=["outlet"], name="monitor_sou_outlet__0bc6c4_idx"),
        ),
        migrations.AddIndex(
            model_name="taglink",
            index=models.Index(fields=["content_type", "object_id"], name="monitor_tag_content__8a0d37_idx"),
        ),
        migrations.AddIndex(
            model_name="topiclink",
            index=models.Index(fields=["atlas_topic_id"], name="monitor_top_atlas_t_4d395b_idx"),
        ),
        migrations.AddIndex(
            model_name="trainingexample",
            index=models.Index(fields=["scope", "created_at"], name="monitor_tra_scope_c_fa2ef4_idx"),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(fields=["time_window_start", "time_window_end"], name="monitor_sto_time_w_d2b66d_idx"),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(fields=["status"], name="monitor_sto_status__32bc24_idx"),
        ),
        migrations.AddIndex(
            model_name="storyarticle",
            index=models.Index(fields=["story", "is_representative"], name="monitor_sto_story_i_b9b144_idx"),
        ),
        migrations.AddIndex(
            model_name="topiclink",
            index=models.Index(fields=["article"], name="monitor_top_article__2f9d2f_idx"),
        ),
        migrations.AddConstraint(
            model_name="actorlink",
            constraint=models.UniqueConstraint(
                fields=("article", "atlas_entity_id", "atlas_entity_type"),
                name="unique_actor_per_article",
            ),
        ),
        migrations.AddConstraint(
            model_name="clientfocus",
            constraint=models.UniqueConstraint(
                fields=("client", "entity_type", "atlas_id"),
                name="unique_client_focus",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyexecution",
            constraint=models.UniqueConstraint(fields=("client", "date"), name="unique_daily_execution"),
        ),
        migrations.AddConstraint(
            model_name="metricaggregate",
            constraint=models.UniqueConstraint(
                fields=("entity_type", "atlas_id", "period", "date_start", "date_end"),
                name="unique_metric_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="storyactor",
            constraint=models.UniqueConstraint(
                fields=("story", "atlas_entity_id", "atlas_entity_type"),
                name="unique_story_actor",
            ),
        ),
        migrations.AddConstraint(
            model_name="storyarticle",
            constraint=models.UniqueConstraint(fields=("story", "article"), name="unique_story_article"),
        ),
        migrations.AddConstraint(
            model_name="taglink",
            constraint=models.UniqueConstraint(fields=("tag", "content_type", "object_id"), name="unique_tag_link"),
        ),
        migrations.AddConstraint(
            model_name="topiclink",
            constraint=models.UniqueConstraint(fields=("article", "atlas_topic_id"), name="unique_topic_per_article"),
        ),
        migrations.AddIndex(
            model_name="dailyexecution",
            index=models.Index(fields=["client"], name="monitor_dai_client__7b6d8b_idx"),
        ),
        migrations.AddIndex(
            model_name="dailyexecution",
            index=models.Index(fields=["date"], name="monitor_dai_date__dc0e7d_idx"),
        ),
        migrations.AddIndex(
            model_name="dailyexecution",
            index=models.Index(fields=["status"], name="monitor_dai_status__46c52f_idx"),
        ),
        migrations.AddIndex(
            model_name="dailyexecution",
            index=models.Index(fields=["client", "date"], name="monitor_dai_client__b1f61e_idx"),
        ),
    ]
