# Generated by Django 5.2.8 on 2025-12-18 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_key', models.CharField(blank=True, max_length=200)),
                ('headline', models.TextField()),
                ('lead', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitor.article')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clusters', to='monitor.ingestrun')),
            ],
        ),
        migrations.CreateModel(
            name='StoryMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('is_base_candidate', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.article')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='monitor.storycluster')),
                ('media_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.mediaoutlet')),
            ],
        ),
        migrations.AddIndex(
            model_name='storycluster',
            index=models.Index(fields=['created_at'], name='monitor_sto_created_5928c7_idx'),
        ),
        migrations.AddIndex(
            model_name='storycluster',
            index=models.Index(fields=['run', 'confidence'], name='monitor_sto_run_id_33a667_idx'),
        ),
        migrations.AddIndex(
            model_name='storymention',
            index=models.Index(fields=['cluster', 'media_outlet'], name='monitor_sto_cluster_9b693e_idx'),
        ),
        migrations.AddConstraint(
            model_name='storymention',
            constraint=models.UniqueConstraint(fields=('cluster', 'article'), name='uniq_cluster_article'),
        ),
    ]
