# Generated by Django 5.2.8 on 2025-12-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailydigestitem',
            index=models.Index(fields=['daily_execution', 'section'], name='monitor_dai_daily_e_9660dc_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialtag',
            index=models.Index(fields=['slug'], name='monitor_edi_slug_98c79e_idx'),
        ),
    ]
