# Generated by Django 5.2.8 on 2025-12-30 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_dailyexecution_monitor_dai_client__7b6d8b_idx_and_more'),
    ]

    operations = [
    ]
