# Generated by Django 5.2.8 on 2025-12-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_storycluster_storymention_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='mediaoutlet',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='storycluster',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='storymention',
            options={'ordering': ['cluster_id', 'media_outlet_id', 'id']},
        ),
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('html_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('date', 'title')},
            },
        ),
    ]
