# Generated by Django 5.2.8 on 2025-12-18 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_article_options_alter_mediaoutlet_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('priority', 'Prioritaria'), ('by_parent', 'Por institución padre'), ('general', 'General')], default='general', max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='monitor.digest')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DigestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('custom_headline', models.TextField(blank=True)),
                ('custom_lead', models.TextField(blank=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.storycluster')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='monitor.digestsection')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('section', 'cluster'), name='uniq_section_cluster')],
            },
        ),
    ]
