# Generated by Django 5.2.8 on 2025-12-18 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_digestsection_digestitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('positivo', 'Positivo'), ('neutro', 'Neutro'), ('negativo', 'Negativo')], max_length=10)),
                ('confidence', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('justification', models.TextField(blank=True)),
                ('model_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='monitor.article')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ContentClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('informative', 'Informativo'), ('opinion', 'Opinión')], max_length=20)),
                ('confidence', models.CharField(default='media', max_length=10)),
                ('justification', models.TextField(blank=True)),
                ('model_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_classification', to='monitor.article')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
