# Generated by Django 5.2.8 on 2025-12-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_articlesentiment_contentclassification'),
    ]

    operations = [
        migrations.AddField(
            model_name='digest',
            name='json_content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
