# Generated by Django 5.2.8 on 2025-12-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_digest_json_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
