# Generated by Django 5.2.8 on 2025-12-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_article_body_text_article_fetched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='article',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
