# Generated by Django 5.2.8 on 2025-12-20 00:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_article_embedding_article_embedding_model'),
        ('redpolitica', '0002_alter_relacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInstitucionMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_alias', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_mentions', to='monitor.article')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_mentions', to='redpolitica.institucion')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('article', 'institucion')},
            },
        ),
        migrations.CreateModel(
            name='ArticlePersonaMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_alias', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_mentions', to='monitor.article')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_mentions', to='redpolitica.persona')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('article', 'persona')},
            },
        ),
        migrations.CreateModel(
            name='InstitucionAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='redpolitica.institucion')),
            ],
            options={
                'ordering': ['alias'],
                'unique_together': {('institucion', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='PersonaAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='redpolitica.persona')),
            ],
            options={
                'ordering': ['alias'],
                'unique_together': {('persona', 'alias')},
            },
        ),
    ]
