# Generated by Django 5.2.8 on 2025-12-20 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_articleinstitucionmention_articlepersonamention_and_more'),
        ('redpolitica', '0002_alter_relacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digest_clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DigestClientConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Síntesis diaria (cliente)', max_length=255)),
                ('top_n', models.PositiveIntegerField(default=7)),
                ('hours', models.PositiveIntegerField(default=48)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='monitor.digestclient')),
                ('instituciones', models.ManyToManyField(blank=True, related_name='digest_client_configs', to='redpolitica.institucion')),
                ('personas', models.ManyToManyField(blank=True, related_name='digest_client_configs', to='redpolitica.persona')),
            ],
        ),
    ]
