# Generated by Django 5.2.8 on 2025-12-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_article_topics_cluster_aggregates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='entitylink',
            new_name='monitor_ent_entity__d8cee3_idx',
            old_name='monitor_ent_entity__5f06d0_idx',
        ),
        migrations.RenameIndex(
            model_name='entitylink',
            new_name='monitor_ent_status_49946d_idx',
            old_name='monitor_ent_status_3791e3_idx',
        ),
        migrations.RenameIndex(
            model_name='mention',
            new_name='monitor_men_article_c520fe_idx',
            old_name='monitor_men_article_6f6e5d_idx',
        ),
        migrations.RenameIndex(
            model_name='mention',
            new_name='monitor_men_normali_1edbda_idx',
            old_name='monitor_men_normali_4ec687_idx',
        ),
    ]
