# Generated by ChatGPT on 2025-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_rename_monitor_ent_entity__5f06d0_idx_monitor_ent_entity__d8cee3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='training_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
