# Generated by Django 5.2.8 on 2026-01-12 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redpolitica", "0012_aliases_as_text"),
        ("sintesis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="synthesisclientinterest",
            name="interest_group",
            field=models.CharField(
                choices=[("priority", "Prioritario"), ("general", "General")],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="synthesisrun",
            name="html_snapshot",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="synthesisrun",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="sintesis/pdfs/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="synthesisrun",
            name="pdf_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="synthesisrun",
            name="stats_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="synthesisstory",
            name="group_label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="synthesisstory",
            name="sentiment_counts_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="synthesisstory",
            name="source_names_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="synthesisstory",
            name="type_counts_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="synthesisstory",
            name="unique_sources_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SynthesisRunSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "group_by",
                    models.CharField(
                        choices=[("story", "Historia"), ("institution", "Institución")],
                        default="story",
                        max_length=20,
                    ),
                ),
                ("stats_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="sintesis.synthesisrun",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="synthesisstory",
            name="run_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stories",
                to="sintesis.synthesisrunsection",
            ),
        ),
        migrations.CreateModel(
            name="SynthesisSectionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "group_by",
                    models.CharField(
                        choices=[("story", "Historia"), ("institution", "Institución")],
                        default="story",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("custom", "Personalizada"),
                            ("by_institution", "Temas por institución"),
                        ],
                        default="custom",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_templates",
                        to="sintesis.synthesisclient",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SynthesisSectionFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "institucion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sintesis_section_filters",
                        to="redpolitica.institucion",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sintesis_section_filters",
                        to="redpolitica.persona",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sintesis_section_filters",
                        to="redpolitica.topic",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filters",
                        to="sintesis.synthesissectiontemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["template", "id"],
            },
        ),
        migrations.AddField(
            model_name="synthesisrunsection",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="run_sections",
                to="sintesis.synthesissectiontemplate",
            ),
        ),
    ]
