# Generated by Django 5.2.8 on 2026-01-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sintesis", "0003_synthesisrun_error_message_and_status_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="synthesisstory",
            name="group_signals_json",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
