# Generated by Django 5.2.8 on 2026-01-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sintesis', '0004_synthesisstory_group_signals_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synthesissectionfilter',
            name='note',
        ),
        migrations.AddField(
            model_name='synthesissectionfilter',
            name='keywords',
            field=models.CharField(blank=True, help_text='Lista de palabras clave o etiquetas separadas por comas.', max_length=500),
        ),
    ]
