# Generated by Django 5.2.8 on 2026-01-14 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
        ("sintesis", "0006_sintesis_refactor_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="synthesissectiontemplate",
            name="contract_keywords_negative",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Palabras clave negativas para excluir artículos.",
            ),
        ),
        migrations.AddField(
            model_name="synthesissectiontemplate",
            name="contract_keywords_positive",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Palabras clave positivas para el contrato de sección.",
            ),
        ),
        migrations.AddField(
            model_name="synthesissectiontemplate",
            name="contract_min_mentions",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Número mínimo de menciones totales si no hay mención fuerte.",
            ),
        ),
        migrations.AddField(
            model_name="synthesissectiontemplate",
            name="contract_min_score",
            field=models.FloatField(
                default=0.6,
                help_text="Score mínimo para aceptar artículos sin mención fuerte.",
            ),
        ),
        migrations.CreateModel(
            name="SynthesisArticleDedup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dedup_key", models.CharField(db_index=True, max_length=128)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dedupe_entries",
                        to="monitor.article",
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deduped_children",
                        to="monitor.article",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dedupe_entries",
                        to="sintesis.synthesisrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SynthesisArticleEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canonical_hash", models.CharField(db_index=True, max_length=64)),
                ("canonical_text", models.TextField()),
                ("embedding_json", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding_cache",
                        to="monitor.article",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SynthesisCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("centroid_json", models.JSONField(default=list)),
                ("top_entities_json", models.JSONField(blank=True, default=list)),
                ("top_tags_json", models.JSONField(blank=True, default=list)),
                ("time_start", models.DateTimeField()),
                ("time_end", models.DateTimeField()),
                ("story_key", models.CharField(blank=True, max_length=128)),
                ("story_title", models.CharField(blank=True, max_length=255)),
                ("story_summary", models.TextField(blank=True)),
                ("key_entities_json", models.JSONField(blank=True, default=list)),
                ("stats_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clusters",
                        to="sintesis.synthesisrun",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clusters",
                        to="sintesis.synthesissectiontemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SynthesisClusterLabelCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("story_key", models.CharField(max_length=128)),
                ("label_date", models.DateField()),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("story_key", "label_date")},
            },
        ),
        migrations.CreateModel(
            name="SynthesisClusterMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity", models.FloatField(default=0.0)),
                ("matched_signals_json", models.JSONField(blank=True, default=list)),
                ("is_strong_match", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_memberships",
                        to="monitor.article",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="sintesis.synthesiscluster",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SynthesisSectionRoutingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_included", models.BooleanField(default=False)),
                ("score", models.FloatField(default=0.0)),
                ("scores_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_results",
                        to="monitor.article",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_results",
                        to="sintesis.synthesisrun",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_results",
                        to="sintesis.synthesissectiontemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SynthesisArticleMentionStrength",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_type", models.CharField(max_length=20)),
                ("target_id", models.IntegerField()),
                ("target_name", models.CharField(max_length=255)),
                (
                    "strength",
                    models.CharField(
                        choices=[("strong", "Fuerte"), ("weak", "Débil")], max_length=10
                    ),
                ),
                ("positions_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mention_strengths",
                        to="monitor.article",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["article", "target_type", "target_id"],
                        name="sintesis_sy_article_1b824a_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="synthesiscluster",
            index=models.Index(
                fields=["run", "template"], name="sintesis_sy_run_id_401348_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="synthesisclustermember",
            unique_together={("cluster", "article")},
        ),
        migrations.AddIndex(
            model_name="synthesissectionroutingresult",
            index=models.Index(
                fields=["run", "template", "article"],
                name="sintesis_sy_run_id_abd4d0_idx",
            ),
        ),
    ]
