# Generated by Django 5.2.8 on 2026-01-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sintesis", "0007_synthesissectiontemplate_contract_keywords_negative_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE EXTENSION IF NOT EXISTS vector;
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name='sintesis_synthesisarticleembedding'
                      AND column_name='embedding_vector'
                ) THEN
                    ALTER TABLE sintesis_synthesisarticleembedding
                    ADD COLUMN embedding_vector vector(1536);
                END IF;
            END$$;
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name='sintesis_synthesiscluster'
                      AND column_name='centroid_vector'
                ) THEN
                    ALTER TABLE sintesis_synthesiscluster
                    ADD COLUMN centroid_vector vector(1536);
                END IF;
            END$$;
            CREATE INDEX IF NOT EXISTS sintesis_embedding_hnsw
                ON sintesis_synthesisarticleembedding
                USING hnsw (embedding_vector vector_cosine_ops);
            CREATE INDEX IF NOT EXISTS sintesis_cluster_hnsw
                ON sintesis_synthesiscluster
                USING hnsw (centroid_vector vector_cosine_ops);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS sintesis_cluster_hnsw;
            DROP INDEX IF EXISTS sintesis_embedding_hnsw;
            ALTER TABLE sintesis_synthesiscluster
                DROP COLUMN IF EXISTS centroid_vector;
            ALTER TABLE sintesis_synthesisarticleembedding
                DROP COLUMN IF EXISTS embedding_vector;
            """,
        ),
    ]
